# Generated by Django 6.0.7 on 2026-08-19 09:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('to', models.CharField(max_length=255)),
                ('cc', models.CharField(blank=True, max_length=255, null=True)),
                ('bcc', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(max_length=1024, verbose_name='subject')),
                ('content', models.TextField(verbose_name='content')),
                ('type', models.CharField(choices=[('HTML', 'HTML'), ('Text', 'text')], default='HTML', max_length=4, verbose_name='type')),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('SENDING', 'sending'), ('SENT', 'sent'), ('FAILED', 'failed')], default='PENDING', max_length=7, verbose_name='status')),
                ('exception', models.TextField(blank=True, null=True, verbose_name='exception')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
