# Generated by Django 6.0.7 on 2026-08-21 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='email',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='email',
            name='exception',
            field=models.TextField(blank=True, null=True, verbose_name='Exception'),
        ),
        migrations.AlterField(
            model_name='email',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=7, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(max_length=1024, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='email',
            name='type',
            field=models.CharField(choices=[('HTML', 'HTML'), ('Text', 'Text')], default='HTML', max_length=4, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='email',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
