# Generated by Django 6.0.7 on 2026-08-14 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_is_verified_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verified_email',
            field=models.BooleanField(default=False, verbose_name='is verified email'),
        ),
    ]
